### ISSUE TITLE
[error] TypeError: Cannot read properties of undefined (reading 'Action')

### ISSUE THREAD

**Issue by thernstig** [ChrisChinchilla/vale-vscode#25]
Version: `v0.18.4`

I get this error in the Extension Host (Remote) when using VS Code remote over ssh:

```
2024-02-12 10:04:04.247 [error] TypeError: Cannot read properties of undefined (reading 'Action')
	at h.provideCodeActions (/home/userA/.vscode-server/extensions/chrischinchilla.vale-vscode-0.18.4/dist/extension.js:2:17830)
	at M.provideCodeActions (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:150:90629)
	at /home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:150:117435
	at ve.s (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:150:112365)
	at ve.$provideCodeActions (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:150:117422)
	at d.S (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:147:5520)
	at d.Q (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:147:5286)
	at d.M (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:147:4338)
	at d.L (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:147:3455)
	at g.value (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:147:2242)
	at r.y (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at r.fire (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at n.fire (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:105:14073)
	at g.value (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:173:8051)
	at r.y (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at r.fire (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at n.fire (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:105:14073)
	at s.z (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:105:17138)
	at g.value (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:105:15590)
	at r.y (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at r.fire (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at g.acceptChunk (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:105:11847)
	at g.value (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:105:11134)
	at r.y (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at r.fire (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at r.z (/home/userA/.vscode-server/bin/31c37ee8f63491495ac49e43b8544550fbae4533/out/vs/workbench/api/node/extensionHostProcess.js:170:19748)
2024-02-12 10:04:18.036 [warning] TextEditor is closed/disposed
2024-02-12 10:11:16.780 [warning] Illegal argument: TextEditor(vs.editor.ICodeEditor:7,$model44)
2024-02-12 10:11:16.855 [warning] Illegal argument: TextEditor(vs.editor.ICodeEditor:7,$model44)
```

**Comment by ChrisChinchilla** [comment]
@thernstig Could you give me a bit more detail? I don't really understand what you mean by "when using VS Code remote over ssh:".

**Comment by thernstig** [comment]
@ChrisChinchilla sure, here you are: https://code.visualstudio.com/docs/remote/ssh

I.e. I am using VS Code over SSH towards a remote. That is why the above error message is shown in the Extension Host (Remote), and not the local Extension Host. Not sure it has any relevance as to why this error occurs, but the information so nothing was missed.

**Comment by thernstig** [comment]
@ChrisChinchilla still issue still exists

**Comment by ChrisChinchilla** [comment]
@thernstig yup, and that's why it's still open. This is a hard edge case for me to test and I haven't had time yet, sorry.

**Comment by thernstig** [comment]
@ChrisChinchilla I see, too bad the logs gave no pointer to what could be faulty.

**Comment by ChrisChinchilla** [comment]
@thernstig 

Dug into this — the crash came from the pre-LSP version of the extension (v0.18.4, the version you reported against).
That entire provider was rewritten from scratch when the extension moved onto vale-ls (the current architecture), so this specific code path no longer exists. I've also gone back through the current implementation and made the equivalent handling explicitly null-safe and unit-tested, so the same class of bug can't reappear silently.

For what it's worth, nothing about the crash or the fix turned out to be SSH-specific — it would have hit identically in a local window whenever an alert had no Action. If you're still seeing crashes on a current version of the extension, please reopen with the version number and a fresh log — otherwise I think this is safe to close.
